apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: registry.cn-qingdao.aliyuncs.com/hellowoodes/api-gateway:1.0.1
          imagePullPolicy: IfNotPresent
          name: gateway
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP