spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #          url-expression: "'http://'+host+':'+port"
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.sprikcngframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud: trace